name: flutter_user_profile_app
description: Flutter User Profile App UI

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  day_night_switcher: ^0.2.0+1
  animate_do: any
  expandable_text: 2.3.0
  flutter_feather_icons: ^2.0.0+1
  url_launcher: ^6.1.3
  shared_preferences: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  

 
    
